### ISSUE TITLE
Комментарии в запросах

### ISSUE THREAD

**Issue by ilovb** [xDrivenDevelopment/sublime-language-1c-bsl#7]
Если закомментировать последнюю строку внутри запроса, то подсветка ломается.

**Comment by nixel2007** [comment]
@ilovb пример можете привести?
Последняя - это какая? На которой строка кавычкой заканчивается?

**Comment by ilovb** [comment]
Да

**Comment by nixel2007** [comment]
@ilovb так в конфигураторе так же. Текст запроса завершается нечетной кавычкой. если ее нет, то весь остальной текст считается строкой.
скрин можете дать?

**Comment by nixel2007** [comment]
Посмотрел, не так же :)
Текст считается пока есть символ `|`. Однако такой код все равно невалидный.

**Comment by ilovb** [comment]
Вот скрин http://hkar.ru/GLEP

**Comment by nixel2007** [comment]
Если я назову это фичей, пойдет? :D 
Как я писал:

> Текст запроса завершается нечетной кавычкой. если ее нет, то весь остальной текст считается строкой.

и оно не скомпилится.

Спасибо, подумаем, что можно сделать в таком случае. Но, имхо, можно оставить так, как внезапную дополнительную проверку структуры кода.

**Comment by ilovb** [comment]
Не скомпилится **где**? В 1С скомпилится ))

**Comment by nixel2007** [comment]
Попробуйте :) Он вам скажет про `Пропущен символ '"' (двойная кавычка)`

**Comment by ilovb** [comment]
Проверил. Все работает. Это же **внутри запроса** коммент.

**Comment by nixel2007** [comment]
ааа, слона-то я и не заметил.
Извиняюсь.
Поправим!

**Comment by ilovb** [comment]
Спасибо!

**Comment by nixel2007** [comment]
Перенес обсуждение в основной репозиторий: https://github.com/xDrivenDevelopment/1c-syntax/issues/93
